
#include "lvgl.h"

/**********************
 *  EXTERN ANIMATION
 **********************/
// Declare the external animation generated by the web tool
extern const lv_img_dsc_t *my_anim_imgs[];
extern const uint16_t my_anim_count;

// Function to create the animation object
void create_custom_anim(lv_obj_t *parent) {
  lv_obj_t *animimg = lv_animimg_create(parent);
  lv_obj_center(animimg);
  lv_animimg_set_src(animimg, (lv_img_dsc_t **)my_anim_imgs, my_anim_count);
  lv_animimg_set_duration(animimg, 1000); // 1000ms total duration
  lv_animimg_set_repeat_count(animimg, LV_ANIM_REPEAT_INFINITE);
  lv_animimg_start(animimg);
}
